name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install-pipenv
        name: Install pipenv
        run: pipx install pipenv
        shell: bash

      - id: install-python
        name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pipenv"

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv install --dev
        shell: bash

      - id: tweet
        name: Tweet
        run: pipenv run python -m tweet cubs
        shell: bash
        env:
            TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
            TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
            TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

